### ISSUE TITLE
Error: Cannot find module 'node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs'

### ISSUE THREAD

**Issue by zhex900** [aws/aws-iot-device-sdk-js-v2#151]
My problem is similar to https://github.com/aws/aws-iot-device-sdk-js-v2/issues/92

But I still cannot find a solution for it. 

I am using electron-forge webpack and typescript template to create a simple electron app.

When using aws-iot-device-sdk-v2 I get this error:

`````
App threw an error during load
Error: Cannot find module '/Users/jake/Code/mir-kiosk-electron/node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs'
    at webpackEmptyContext (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:594:10)
    at Object.<anonymous> (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:1086:91)
    at Object../node_modules/aws-crt/dist/native/binding.js (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:1095:30)
    at __webpack_require__ (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:21:30)
    at Object../node_modules/aws-crt/dist/native/crt.js (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:1128:35)
    at __webpack_require__ (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:21:30)
    at Object../node_modules/aws-crt/dist/index.js (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:566:26)
    at __webpack_require__ (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:21:30)
    at Object../node_modules/aws-iot-device-sdk-v2/dist/greengrass/discoveryclient.js (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:2508:19)
    at __webpack_require__ (/Users/jake/Code/mir-kiosk-electron/.webpack/main/index.js:21:30)
No issues found.
```````

`/Users/jake/Code/mir-kiosk-electron/node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs` is a correct path
The file is there. 

in `binding.js`
I will get the same error even if I make this change

````
for (const path of search_paths) {
    if (fs_1.existsSync(path + '.node')) {
        binding = require(path+ '.node'); // added + '.node'
        break;
    }
}
```````
I think is a webpack thing. 

Envrionment: 
Mac OS: Big Sur
Node: v14.15.2, same problem as v14.16

I can get `aws-iot-device-sdk-js-v2` working without typescript and webpack. So I pretty sure my webpack is not configured correctly. 

Can you help?

I also posted my question here
https://stackoverflow.com/questions/67354489/webpack-changed-dirname-in-node-modules

**Comment by zhex900** [comment]
I solved it. 

I had to remove this package `@marshallofsound/webpack-asset-relocator-loader`
