### ISSUE TITLE
Error: Cannot find module 'node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs'

### ISSUE THREAD

**Issue by zhex900** [aws/aws-iot-device-sdk-js-v2#152]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Mac OS Big Sur

**Describe the question**
https://github.com/zhex900/electron-aws-iot

I am trying to get AWS iot sdk to work with electron using typescript and webpack. 

After I added webpack, I got this error. 

````
webpack built 0be18683b3f1abe58514 in 260ms
App threw an error during load
Error: Cannot find module '/Users/jake/Code/electron-aws-iot/node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs'
    at webpackEmptyContext (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:583:10)
    at Object.<anonymous> (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:1075:91)
    at Object../node_modules/aws-crt/dist/native/binding.js (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:1084:30)
    at __webpack_require__ (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:21:30)
    at Object../node_modules/aws-crt/dist/native/crt.js (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:1117:35)
    at __webpack_require__ (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:21:30)
    at Object../node_modules/aws-crt/dist/index.js (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:555:26)
    at __webpack_require__ (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:21:30)
    at Object../node_modules/aws-iot-device-sdk-v2/dist/greengrass/discoveryclient.js (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:2497:19)
    at __webpack_require__ (/Users/jake/Code/electron-aws-iot/.webpack/main/index.js:21:30)
Issues checking in progress...
No issues found.
````

`/Users/jake/Code/electron-aws-iot/node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs` is valid 

I don't know why it cannot find it.

**Comment by zhex900** [comment]
I fixed it. 

I used https://www.npmjs.com/package/webpack-node-externals
