### ISSUE TITLE
fleet provisioning on windows 

### ISSUE THREAD

**Issue by zhex900** [aws/aws-iot-device-sdk-js-v2#165]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
I running `fleet_provisioning` in the examples. 

```
node ./dist/index.js --endpoint $IOT_ENDPOINT --ca_file ./AmazonRootCA1.pem --cert ./.certificate.pem --key ./.private.key --template_name fleet-provisioning-template --template_parameters "{\"SerialNumber\":\"297468\",\"ModelType\":\"Berlin\"}" --client_id fleet-device
```

This is working on my Mac. But when I run the same code in windows. I get this error:

Do I need to register the AWS CA on windows? Or I need to install some form of `openssl` on windows?
```
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolving host a2c20hllaiyqiw-ats.iot.ap-southeast-2.amazonaws.com
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 3.105.169.146
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 13.239.123.223
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 52.62.213.19
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 52.64.35.72
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 52.63.84.71
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 3.104.28.136
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 13.239.157.170
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static: resolved record: 52.64.8.190
[DEBUG] [2021-06-17T11:53:17Z] [000017c0] [dns] - static, resolving host a2c20hllaiyqiw-ats.iot.ap-southeast-2.amazonaws.com successful, returned 8 addresses
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [socket] - id=000001D2FA7F4590 handle=000000000000032C: setting socket options to: keep-alive 0, keep idle 0, keep-alive interval 0, max failed probe count 0
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [socket] - id=000001D2FA7F4590 handle=000000000000032C: connection success
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [socket] - id=000001D2FA7F4590 handle=000000000000032C: local endpoint 10.211.55.7:55540
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel-bootstrap] - id=000001D2F8BF43C0: client connection on socket 000001D2FA7F4590 completed with error 0.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: Beginning creation and setup of new channel.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [task-scheduler] - id=000001D2F8BF54E0: Scheduling on_channel_setup_complete task for immediate execution
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [task-scheduler] - id=000001D2F8BF54E0: Running on_channel_setup_complete task with <Running> status
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: setup complete, notifying caller.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: no message pool is currently stored in the event-loop local storage, adding 000001D2F8DEAD80 with max message size 16384, message count 4, with 4 small blocks of 128 bytes.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel-bootstrap] - id=000001D2F8BF43C0: channel 000001D2FA7EC5D0 setup succeeded: bootstrapping.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [socket-handler] - id=000001D2F8DE8370: Socket handler created with max_read_size of 16384
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: Setting SNI to a2c20hllaiyqiw-ats.iot.ap-southeast-2.amazonaws.com
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: Kicking off TLS negotiation
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [task-scheduler] - id=000001D2FA81B370: Scheduling tls_timeout task for future execution at time 28961400137900
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - static: This library was built with Windows 8.1 or later, probing OS to see what we're actually running on.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - static: We're running on Windows 8.1 or later. ALPN is available.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: Setting ALPN data as x-amzn-mqtt-ca
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] -
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - Setting ALPN extension with string x-amzn-mqtt-ca.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: manually verifying certifcate chain because a custom CA is configured.
[ERROR] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: certificate verification failed, error 0x80092013
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel-bootstrap] - id=000001D2F8BF43C0: tls negotiation result 1029 on channel 000001D2FA7EC5D0
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [task-scheduler] - id=000001D2FA7EC7B0: Scheduling channel_shutdown task for immediate execution
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: Channel shutdown is already pending, not scheduling another.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: Channel shutdown is already pending, not scheduling another.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [task-scheduler] - id=000001D2FA7EC7B0: Running channel_shutdown task with <Running> status
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: beginning shutdown process
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [channel] - id=000001D2FA7EC5D0: handler 000001D2F8DE8370 shutdown in read dir completed.
events.js:353
      throw er; // Unhandled 'error' event
      ^

CrtError: Failed to connect: aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
    at Y:\Code\mir-kiosk-electron\infra\fleetProvisioning\fleet_provisioning\node_modules\aws-crt\dist\native\mqtt.js:333:36
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event on MqttClientConnection instance at:
    at MqttClientConnection.emit (Y:\Code\mir-kiosk-electron\infra\fleetProvisioning\fleet_provisioning\node_modules\aws-crt\dist\common\event.js:76:22)
    at Y:\Code\mir-kiosk-electron\infra\fleetProvisioning\fleet_provisioning\node_modules\aws-crt\dist\native\mqtt.js:333:22
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  error: 'Failed to connect: aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed',
  error_code: undefined,
  error_name: undefined
}
```

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Windows 10 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
const level : io.LogLevel = parseInt(io.LogLevel[argv.verbosity.toUpperCase()]);
io.enable_logging(level);
```

**Additional context**
````
#fleet-provisioning-template
{
  "Parameters": {
    "SerialNumber": {
      "Type": "String"
    },
    "ModelType": {
      "Type": "String"
    },
    "AWS::IoT::Certificate::Id": {
      "Type": "String"
    }
  },
  "Resources": {
    "certificate": {
      "Properties": {
        "CertificateId": {
          "Ref": "AWS::IoT::Certificate::Id"
        },
        "Status": "Active"
      },
      "Type": "AWS::IoT::Certificate"
    },
    "policy": {
      "Properties": {
        "PolicyName": "fullCitizenPolicy"
      },
      "Type": "AWS::IoT::Policy"
    },
    "thing": {
      "OverrideSettings": {
        "AttributePayload": "MERGE",
        "ThingGroups": "DO_NOTHING",
        "ThingTypeName": "REPLACE"
      },
      "Properties": {
        "AttributePayload": {
          "model_type": {
            "Ref": "ModelType"
          }
        },
        "ThingGroups": [],
        "ThingName": {
          "Ref": "SerialNumber"
        }
      },
      "Type": "AWS::IoT::Thing"
    }
  }
}
````

**Comment by jmklix** [comment]
Try following these [detailed fleet provisioning instructions](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/fleet-provisioning-docs/samples#fleet-provisioning-detailed-instructions). Please let me know if you have any trouble with them.

**Comment by zhex900** [comment]
I have already done that. My setup works on Mac but I have problem on windows. 

```
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - Setting ALPN extension with string x-amzn-mqtt-ca.
[DEBUG] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: manually verifying certifcate chain because a custom CA is configured.
[ERROR] [2021-06-17T11:53:17Z] [0000167c] [tls-handler] - id=000001D2FA81B340: certificate verification failed, error 0x80092013
````

**Comment by bretambrose** [comment]
This is fixed in the latest CRT and should be fixed in the next v2 SDK release when we bump the crt version.

**Comment by zhex900** [comment]
Do you have an ETA for the next release?

**Comment by bretambrose** [comment]
1.5.2 should contain the fix and be in npm shortly.
