### ISSUE TITLE
How to shutdown the client gracefully

### ISSUE THREAD

**Issue by imZack** [aws/aws-iot-device-sdk-js-v2#218]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?
macOS

**Describe the question**

Is there a way that we can close the connection gracefully not interrupting the in-flight messages and causing `Failed to publish: libaws-c-mqtt: AWS_ERROR_MQTT_CONNECTION_DESTROYED, Connection has started destroying process, all uncompleted requests will fail.`

I've seen something similar at https://github.com/aws/aws-iot-device-sdk-js-v2/pull/201 . Not sure if it's the best option we have today?

**Comment by jmklix** [comment]
How are you currently trying to shutdown the client?

You don't have to use the timer as shown in the pubsub sample (as that is just because the pubsub is only meant to run for a short time). Just using `await connection.disconnect()` should work for you.

**Comment by imZack** [comment]
Hello @jmklix, thanks for your reply.

I'm using `await connection.disconnect()` as you mentioned. However, if there is still something working on publishing  (e.g., waiting for ACK if it's QoS 1/2). I'll get the error `AWS_ERROR_MQTT_CONNECTION_DESTROYED`.

**Comment by jmklix** [comment]
This sdk doesn't support QoS 2 currently. How often are you running into this error? You shouldn't be trying to publish anymore after you have disconnected the client. Can you also attach some logs from when it happens to you?

**Comment by imZack** [comment]
The program I wrote runs every 15 minutes and it happens about 1x times per week.
I have a connection flag to prevent publishing after triggering shutting down but still can't prevent this happen.


Some logs for your reference
```
2022-02-14T13:20:49.407Z 3a818d98-cb12-42f4-a571-af86b4fb348a ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Failed to publish: libaws-c-mqtt: AWS_ERROR_MQTT_CONNECTION_DESTROYED, Connection has started destroying process, all uncompleted requests will fail.","reason":"Failed to publish: libaws-c-mqtt: AWS_ERROR_MQTT_CONNECTION_DESTROYED, Connection has started destroying process, all uncompleted requests will fail.","promise":{},"stack":["Runtime.UnhandledPromiseRejection: Failed to publish: libaws-c-mqtt: AWS_ERROR_MQTT_CONNECTION_DESTROYED, Connection has started destroying process, all uncompleted requests will fail."," at process.<anonymous> (/var/runtime/index.js:35:15)"," at process.emit (events.js:412:35)"," at process.emit (domain.js:475:12)"," at processPromiseRejections (internal/process/promises.js:245:33)"," at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
--
```

**Comment by jmklix** [comment]
Is your program running every 15 minutes or just publishing every 15 minutes?

**Comment by jmklix** [comment]
Are you using a promise to wait for your publishes to finish like in the pub_sub with `execute_session`?

**Comment by imZack** [comment]
Sounds like I need to have a queue for processing pub/disconnect to prevent there is something still on-going.
