### ISSUE TITLE
npm install node dist/index.js --endpoint <endpoint> --ca_file <file> --cert <file> --key <file> this command is not working

### ISSUE THREAD

**Issue by harleenkbhatia** [aws/aws-iot-device-sdk-js-v2#251]
### Describe the issue

after npm install in this command
node dist/index.js --endpoint <endpoint> --ca_file <file> --cert <file> --key <file> 

dist/index.js is not accessible whenever I am running this code this is the error that is coming

\aws-iot-device-sdk-js-v2\node_modules\yargs\lib\parser.js:66
  if (args.indexOf('--') !== -1) {
           ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at module.exports (C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\node_modules\yargs\lib\parser.js:66:12)
    at parseArgs (C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\node_modules\yargs\index.js:512:18)
    at Object.Argv.self.parse (C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\node_modules\yargs\index.js:285:12)     
    at Object.<anonymous> (C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\samples\node\pub_sub_js\index.js:15:10)     
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12node .\node\pub_sub_js\index.js --endpoint <endpoint> --ca_file <file> --key aws-video\aws-iot-device-sdk-js-v2\DEFAULT-DEVICE\private_key_DEFAULT-DEVICE.key^CSL\aws-video\aws-iot-device-sdk-js-v2\samples>
PS C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\samples> node dist/index.js --endpoint <endpoint> --ca_file <file> --key <file>
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\samples\dist\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### Links

https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples

**Comment by TwistedTwigleg** [comment]
Are you running the sample using `node dist/index.js --endpoint --ca_file --cert --key` exactly? You need to fill in the parameters for each of the arguments for the sample to work, as otherwise it will not know where to go to make a connection. For example, here's what a fully inputted command might look like (using a fake endpoint):

~~~
node dist/index.js --endpoint abcdefghijklmno-ats.iot.us-east-1.amazonaws.com --ca_file /home/users/username/certs/ca_file.pem --cert /home/users/username/certs/cert.pem --key /home/users/username/certs/key-private.pem.key
~~~

Can you share the arguments you are passing to the command line? Please replace any sensitive data with substitutes, like setting the endpoint you are using to `<endpoint>`. Based on the error, I think what is happening is the data being passed to the sample is incorrect.

**Comment by harleenkbhatia** [comment]
> Are you running the sample using `node dist/index.js --endpoint --ca_file --cert --key` exactly? You need to fill in the parameters for each of the arguments for the sample to work, as otherwise it will not know where to go to make a connection. For example, here's what a fully inputted command might look like (using a fake endpoint):
> 
> ```
> node dist/index.js --endpoint abcdefghijklmno-ats.iot.us-east-1.amazonaws.com --ca_file /home/users/username/certs/ca_file.pem --cert /home/users/username/certs/cert.pem --key /home/users/username/certs/key-private.pem.key
> ```
> 
> Can you share the arguments you are passing to the command line? Please replace any sensitive data with substitutes, like setting the endpoint you are using to `<endpoint>`. Based on the error, I think what is happening is the data being passed to the sample is incorrect.

I did it with the relative paths... removed them before posting here but now I tried again with their paths and now this is the error that's coming: 

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Hitech\THRSL\aws-video\aws-iot-device-sdk-js-v2\samples\dist\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
