### ISSUE TITLE
GLIBC Error when running node application

### ISSUE THREAD

**Issue by markl-vesper** [aws/aws-iot-device-sdk-js-v2#26]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Describe the bug**
Installed sdk v2 along with aws-crt as per readme and getting error when running device-example.js

 node device-example.js
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/ec2-user/aws/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ec2-user/aws/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/native/binding.js:53:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

SDK V1.0.3

**Platform/OS/Hardware/Device**
What are you running the sdk on?

aws linux ec2

**To Reproduce (observed behavior)**
npm install --save aws-crt
npm install --save aws-iot-device-sdk-v2
node device-example.js (with reqd params)

**Expected behavior**
Expected the app to connect to IoT using the certificates provided

**Logs/output**
as above

**Comment by markl-vesper** [comment]
realised that maybe example code from v1 sdk might not work so I tried pub sub example

npm install
node dist/index.js

same error re GLIBC_2.25 not found

**Comment by JonathanHenson** [comment]
by aws linux do you mean AL2012 or AL2?

**Comment by JonathanHenson** [comment]
anyways, what this means is you successfully found the prebuilt node module, but the node module was built on a linux distro that was too new. This is probably a bug on our side since we're supposed to be building this stuff on an ancient distro. We'll track it down for you.

**Comment by markl-vesper** [comment]
> by aws linux do you mean AL2012 or AL2?

EC2 describes the AMI as 

amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2 (ami-02fd0b06f06d93dfc)

**Comment by justinboswell** [comment]
Once https://github.com/awslabs/aws-crt-nodejs/pull/66 is approved, I'll push a new release to npm

**Comment by justinboswell** [comment]
https://github.com/aws/aws-iot-device-sdk-js-v2/pull/28

**Comment by accnops** [comment]
I've got the same error on the official NodeJS Docker images. I tried `node:12.16.2-slim` and `node:12.16.2`.

The error is thrown when importing aws-crt. `import { mqtt, io, iot } from 'aws-crt'`

I tried adding various packages to the Docker container solve the issue (g++, libc6, cmake, ...), without success.

Here's the full error:
```internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/aws-crt/dist/native/binding.js:53:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/aws-crt/dist/native/crt.js:20:35)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)```

**Comment by accnops** [comment]
I created a reproducible example:

File `index.js`:
```
require('aws-crt');
```

File `Dockerfile`:
```
FROM node:12.16.2
RUN npm install aws-crt@1.1.2
COPY index.js .
CMD ["node", "index.js"]
```

Command:
`docker build -t aws-crt-test . && docker run aws-crt-test`

Error:
```
internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/aws-crt/dist/native/binding.js:53:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```

**Comment by justinboswell** [comment]
I'm looking into this, might need to adjust our precompile images.

**Comment by justinboswell** [comment]
Ok, looks like the official nodejs images use glibc 2.24. I'll fix our images and roll a new release, thank you for distilling this down into a good repro.

**Comment by justinboswell** [comment]
Waiting on https://github.com/awslabs/aws-crt-nodejs/pull/74 and then I will publish a new release.

**Comment by justinboswell** [comment]
https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.1.3

Release should be on npm in an hour or so.

**Comment by accnops** [comment]
Works! Thanks a lot!

Do you know if Alpine Linux is supported?

When using the example above and Dockerfile:
```
FROM node:12.16.2-alpine
RUN apk add gcompat
RUN npm install aws-crt@1.1.3
COPY index.js .
CMD ["node", "index.js"]
```

It seems like `aws-crt` is "hijacking" the process, and printing:
```
Signal received: 32, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
...
```
And then exiting. Any thoughts?

**Comment by justinboswell** [comment]
Yeah, right now, we do not have an alpine target where we link against libmusl, if you attached a debugger what you would see is a crash because none of the glibc symbols can be found when loading our node binary. You would likely be able to get it working on alpine with https://github.com/sgerrand/alpine-pkg-glibc, but that's obviously not ideal. 

If you need alpine support, can you open a feature request issue just for that so people can vote for it and we can get it prioritized.
