### ISSUE TITLE
MQTT Connection Closed

### ISSUE THREAD

**Issue by TusharBudhirajaDev** [aws/aws-iot-device-sdk-js-v2#503]
### Describe the bug

Hey I am using aws-iot-device-sdk-v2 in my Angular application on frontend side, I create a client using this sdk, so while using this my client create using following parameters:
1. accessKeyId
2. secretKey
3. host
4. clientId
5. region
6. sessionToken

My client has been created successfully, and my **connect** event is working fine but before **message** event is called, I get an error of connection close like this 

Error: Error: **Connection closed**
    at new CrtError (error.js:34:1)
    at MqttClientConnection._this.on_error (mqtt.js:271:1)
    at mqtt.js:475:1
    at Object.cb (client.js:831:1)
    at client.js:198:1
    at Array.forEach (<anonymous>)
    at flushVolatile (client.js:196:1)
    at Duplexify.<anonymous> (client.js:469:1)
    at Duplexify.emit (events.js:153:1)
    at push.+xLd.Duplexify._destroy (index.js:199:1)errorr...... Error: Error: Connection closed
    at new CrtError (error.js:34:1)
    at MqttClientConnection._this.on_error (mqtt.js:271:1)
    at mqtt.js:475:1
    at Object.cb (client.js:831:1)
    at client.js:198:1
    at Array.forEach (<anonymous>)
    at flushVolatile (client.js:196:1)
    at Duplexify.<anonymous> (client.js:469:1)
    at Duplexify.emit (events.js:153:1)
    at push.+xLd.Duplexify._destroy (index.js:199:1)

### Expected Behavior

My message event should be working according to documentation given by aws

### Current Behavior

Throwing error

Error: Error: Connection closed
    at new CrtError (error.js:34:1)
    at MqttClientConnection._this.on_error (mqtt.js:271:1)
    at mqtt.js:475:1
    at Object.cb (client.js:831:1)
    at client.js:198:1
    at Array.forEach (<anonymous>)
    at flushVolatile (client.js:196:1)
    at Duplexify.<anonymous> (client.js:469:1)
    at Duplexify.emit (events.js:153:1)
    at push.+xLd.Duplexify._destroy (index.js:199:1)errorr...... Error: Error: Connection closed
    at new CrtError (error.js:34:1)
    at MqttClientConnection._this.on_error (mqtt.js:271:1)
    at mqtt.js:475:1
    at Object.cb (client.js:831:1)
    at client.js:198:1
    at Array.forEach (<anonymous>)
    at flushVolatile (client.js:196:1)
    at Duplexify.<anonymous> (client.js:469:1)
    at Duplexify.emit (events.js:153:1)
    at push.+xLd.Duplexify._destroy (index.js:199:1)

### Reproduction Steps

const client = this.getClient(iotInput);
        let counter = 0;

        client.on('connect', () => {
            console.log('$$$', iotInput);

            client.subscribe(iotInput.topic, 1);
            iotInput.connectionSuccessCallback();
            console.log('connecting......');
        });

        client.on('message', (topic, message) => {
            const data = new TextDecoder('utf-8').decode(message);
            console.log('message......', data);
           }

### SDK version used

1.16.1

### Environment details (OS name and version, etc.)

facing issue on both window and mac(ios) as well

**Comment by bretambrose** [comment]
Please provide full, minimal standalone repro.  The code snippet is insufficient.

In general, a reliable connection closed behavior is usually due to incorrect permissions on the IAM policy that is associated with the credentials used to establish the websocket connection.  What is the policy you are using?

**Comment by TusharBudhirajaDev** [comment]
This issues has been debugged, Its a  IAM policy. Thanks for helping
