### ISSUE TITLE
AWS IoT Core onboarding no longer works.

### ISSUE THREAD

**Issue by Jcrash29** [aws/aws-iot-device-sdk-js-v2#56]
**Describe the bug**
When using the onboarding tool of AWS IoT Core it creates a package for exececuting on your device. It includes the certs and a startup.sh which pulls this project. With the switch to the new SDK the code no longer executes properly.

**Platform/OS/Hardware/Device**
Ubuntu 16.04

**To Reproduce (observed behavior)**
Attempt to onboard a device with Linux and nodeJS. 

The start up script is as follows:

```
# stop script on error
set -e

# Check to see if root CA file exists, download if not
if [ ! -f ./root-CA.crt ]; then
  printf "\nDownloading AWS IoT Root CA certificate from AWS...\n"
  curl https://www.amazontrust.com/repository/AmazonRootCA1.pem > root-CA.crt
fi

CWD=`pwd`

# install AWS Device SDK for NodeJS if not already installed + pubsub sample
if [ ! -d ./aws-iot-device-sdk-js-v2 ]; then
  printf "\nInstalling AWS SDK...\n"
  git clone https://github.com/aws/aws-iot-device-sdk-js-v2.git
  cd aws-iot-device-sdk-js-v2
  npm install
  # samples require their own install
  cd samples/node/pub_sub
  npm install
  cd $CWD
fi

# run pub/sub sample app using certificates downloaded in package
printf "\nRunning pub/sub sample application...\n"
node aws-iot-device-sdk-js-v2/samples/node/pub_sub/dist/index.js --endpoint auise9zxx6bhb-ats.iot.us-west-2.amazonaws.com --key VanteonDemo_website.private.key --cert VanteonDemo_website.cert.pem --ca_file root-CA.crt --client_id sdk-nodejs-v2 --topic topic_1

```

Appears to me that the folder structure has now changed, (remove /dist/) the `index.js` has also changed to a `index.ts`.

**Expected behavior**
startup.sh should complete and start the pub-sub example so the IoT Core can view the resulting messages.

**Comment by jmklix** [comment]
I'm having difficulty reproducing an error while using the AWS IoT Core package. Could you download it to a new folder and then reply with the error that you get?

**Comment by Jcrash29** [comment]
I downloaded a new on-boarding package from the AWS IoTCore. It contains the following files:

```
$ ls
GithubTest.cert.pem GithubTest.private.key GithubTest.public.key root-CA.crt start.sh
```

I execute the `start.sh`

```
$./start.sh

Running pub/sub sample application...

module.js:328
    throw err;
    ^

Error: Cannot find module '/home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/samples/node/pub_sub/dist/index.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by bretambrose** [comment]
What platform is this on?  Are you able to copy the entire output of the start.sh file run?

**Comment by Jcrash29** [comment]
Here is the full output from the first time executing the command:

```
Installing AWS SDK...
Cloning into 'aws-iot-device-sdk-js-v2'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (254/254), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 537 (delta 194), reused 187 (delta 148), pack-reused 283
Receiving objects: 100% (537/537), 577.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (333/333), done.
Checking connectivity... done.
loadDep:readable-stream → ▄ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDevDep:typescript → 3 ▌ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:typedoc-default-t ▐ ╢███████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:typedoc-default-t ▀ ╢███████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:typedoc-default-t ▀ ╢███████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> aws-crt@1.1.5 install /home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/node_modules/aws-crt
> node ./scripts/install.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'cmake-js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/node_modules/aws-crt/scripts/build.js:17:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
aws-iot-device-sdk-v2@1.0.0-dev /home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2
├── @convergencelabs/typedoc-plugin-custom-modules@0.4.0 
├── @types/node@10.17.26 
├─┬ typedoc@0.17.7 
│ ├─┬ fs-extra@8.1.0 
│ │ ├── graceful-fs@4.2.4 
│ │ ├── jsonfile@4.0.0 
│ │ └── universalify@0.1.2 
│ ├─┬ handlebars@4.7.6 
│ │ ├── minimist@1.2.5 
│ │ ├── neo-async@2.6.1 
│ │ ├── source-map@0.6.1 
│ │ ├── uglify-js@3.10.0 
│ │ └── wordwrap@1.0.0 
│ ├── highlight.js@10.1.1 
│ ├── lodash@4.17.15 
│ ├── lunr@2.3.8 
│ ├── marked@1.0.0 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.11 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├── progress@2.0.3 
│ ├─┬ shelljs@0.8.4 
│ │ ├─┬ glob@7.1.6 
│ │ │ ├── fs.realpath@1.0.0 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ ├── inherits@2.0.4 
│ │ │ ├── once@1.4.0 
│ │ │ └── path-is-absolute@1.0.1 
│ │ ├── interpret@1.4.0 
│ │ └─┬ rechoir@0.6.2 
│ │   └─┬ resolve@1.17.0 
│ │     └── path-parse@1.0.6 
│ └── typedoc-default-themes@0.10.1 
└── typescript@3.9.5 

npm ERR! Linux 4.15.0-106-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! aws-crt@1.1.5 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-crt@1.1.5 install script 'node ./scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-crt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-crt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-crt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/npm-debug.log
```

After this I attempt to install `cmake-js`

```
sudo npm install -g cmake-js
```

(I'll get that output at a later date)

**Comment by Jcrash29** [comment]
I think I see the issue, once I install cmake-js instead of calling ./startup.sh, I'll need to call 

```
cd aws-iot-device-sdk-js-v2
npm install
```

and install the pub_sub  application. Will let you know how that goes.

**Comment by bretambrose** [comment]
What versions of node and npm are you using?

**Comment by Jcrash29** [comment]
It appears that in Ubuntu 16.04 these are the latest versions accesible using apt-get

```
peta@peta-VirtualBox:~/Desktop/GitHubTest/aws-iot-device-sdk-js-v2$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  ubuntu-desktop
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

peta@peta-VirtualBox:~/Desktop/GitHubTest/aws-iot-device-sdk-js-v2$ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

peta@peta-VirtualBox:~/Desktop/GitHubTest/aws-iot-device-sdk-js-v2$ sudo apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (3.5.2-0ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded
```


After executing `sudo npm install -g cmake-js`

I attempted to re-run `npm install`:

```
peta@peta-VirtualBox:~/Desktop/GitHubTest/aws-iot-device-sdk-js-v2$ npm install
loadDep:readable-stream → ▐ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> aws-crt@1.1.5 install /home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/node_modules/aws-crt
> node ./scripts/install.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'cmake-js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/node_modules/aws-crt/scripts/build.js:17:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
npm ERR! Linux 4.15.0-106-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! aws-crt@1.1.5 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-crt@1.1.5 install script 'node ./scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-crt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-crt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-crt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peta/Desktop/GitHubTest/aws-iot-device-sdk-js-v2/npm-debug.log
```

I'll look into installing a more recent nodejs and npm using a different method.

**Comment by jmklix** [comment]
Are you still having issues with the IoT core onboarding?
