### ISSUE TITLE
pubsub sample does not work out of the box.

### ISSUE THREAD

**Issue by Th3G4mbl3r** [aws/aws-iot-device-sdk-js-v2#57]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Describe the bug**
As instructed in the README.md, i downloaded a zip file version of the master branch. I went into the pubsub sample directory and ran the following commands:

,,,
npm install

node dist/index.js --endpoint akom112at41zv-ats.iot.us-west-2.amazonaws.com --root-ca certs/AmazonRootCA1.p
em --cert certs/pressure_valve_1_ca_cert.crt --key certs/pressure_valve_1.key
,,,
**SDK version number**
aws-crt 1.1.1
aws-iot-device-sdk-v2 is based on the current master branch as of today.

**Platform/OS/Hardware/Device**
MacOS Catalina 10.15.5 and node 10.21.0

**To Reproduce (observed behavior)**
Based on the out of the box pubsub sample from the git repository.

**Expected behavior**
The sample to run successfully and correctly.

**Logs/output**
If applicable, add logs or error output.

```
[ERROR] [2020-06-17T12:30:58Z] [0000700011f67000] [socket] - id=0x102a27080 fd=70: connect failed with error code 65.
[ERROR] [2020-06-17T12:30:58Z] [0000700011f67000] [channel-bootstrap] - id=0x102d12650: failed to create socket with error 1049
[ERROR] [2020-06-17T12:30:59Z] [0000700011f67000] [tls-handler] - id=0x102b24720: error reported during SSLRead. OSStatus code -9805
N-API call failed: napi_call_function(env, this_ptr, function, argc, argv, NULL)
    @ /Users/Shared/Jenkins/Home/workspace/aws-crt-nodejs-osx-x64/aws-crt-nodejs/source/module.c:376: napi_pending_exception
Calling (error_code, return_code, session_present) => {
                    if (error_code == 0 && return_code == 0) {
                        resolve(session_present);
                        this.emit('connect', session_present);
                    }
                    else if (error_code != 0) {
                        reject("Failed to connect: " + io.error_code_to_string(error_code));
                    }
                    else {
                        reject("Server rejected connection.");
                    }
                }
Error: Failed to connect: libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
Stack:
Error: Failed to connect: libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
    at /Users/rohitus/Documents/Projects/node-aws-iot-samples/aws-iot-device-sdk-js-v2-master/node_modules/aws-crt/dist/native/mqtt.js:241:32
    at on_connect (/Users/rohitus/Documents/Projects/node-aws-iot-samples/aws-iot-device-sdk-js-v2-master/node_modules/aws-crt/dist/native/mqtt.js:111:25)
N-API call failed: aws_napi_dispatch_threadsafe_function(env, args->on_connect, NULL, on_connect, num_params, params)
    @ /Users/Shared/Jenkins/Home/workspace/aws-crt-nodejs-osx-x64/aws-crt-nodejs/source/mqtt_client_connection.c:300: napi_pending_exception
Fatal error condition occurred in /Users/Shared/Jenkins/Home/workspace/aws-crt-nodejs-osx-x64/aws-crt-nodejs/source/mqtt_client_connection.c:300: aws_napi_dispatch_threadsafe_function(env, args->on_connect, NULL, on_connect, num_params, params)
Exiting Application
################################################################################
Resolved stacktrace:
################################################################################
1   aws-crt-nodejs.node                 0x0000000102f70866 aws_fatal_assert + 70
2   aws-crt-nodejs.node                 0x0000000102f25bec s_on_connect_call + 508
(anonymous namespace)::v8impl::ThreadSafeFunction::IdleCb(uv_idle_s*) (in node) + 413
uv__run_idle (in node) + 148
uv_run (in node) + 320
node::Start(v8::Isolate*, node::IsolateData*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (in node) + 946
node::Start(uv_loop_s*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (in node) + 329
node::Start(int, char**) (in node) + 681
start (in node) + 52
################################################################################
Raw stacktrace:
################################################################################
1   aws-crt-nodejs.node                 0x0000000102f70866 aws_fatal_assert + 70
2   aws-crt-nodejs.node                 0x0000000102f25bec s_on_connect_call + 508
3   node                                0x000000010004afb9 _ZN12_GLOBAL__N_16v8impl18ThreadSafeFunction6IdleCbEP9uv_idle_s + 413
4   node                                0x00000001009dccd2 uv__run_idle + 148
5   node                                0x00000001009d7707 uv_run + 320
6   node                                0x0000000100041ef0 _ZN4node5StartEPN2v87IsolateEPNS_11IsolateDataERKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENSA_ISC_EEEESG_ + 946
7   node                                0x0000000100040f83 _ZN4node5StartEP9uv_loop_sRKNSt3__16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEESD_ + 329
8   node                                0x0000000100040c45 _ZN4node5StartEiPPc + 681
9   node                                0x0000000100001034 start + 52
Signal received: 6, errno: 0
################################################################################
Resolved stacktrace:
################################################################################
1   aws-crt-nodejs.node                 0x0000000102f23ee3 s_print_stack_trace + 19
2   libsystem_platform.dylib            0x00007fff70c1a5fd _sigtramp + 29
3   aws-crt-nodejs.node                 0x0000000102fb0008 aws_is_debugger_present.tracerPidString + 11000
4   libsystem_c.dylib                   0x00007fff70af0808 abort + 120
5   aws-crt-nodejs.node                 0x0000000102f7086b aws_fatal_assert + 75
6   aws-crt-nodejs.node                 0x0000000102f25bec s_on_connect_call + 508
(anonymous namespace)::v8impl::ThreadSafeFunction::IdleCb(uv_idle_s*) (in node) + 413
uv__run_idle (in node) + 148
uv_run (in node) + 320
node::Start(v8::Isolate*, node::IsolateData*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (in node) + 946
node::Start(uv_loop_s*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) (in node) + 329
node::Start(int, char**) (in node) + 681
start (in node) + 52
################################################################################
Raw stacktrace:
################################################################################
1   aws-crt-nodejs.node                 0x0000000102f23ee3 s_print_stack_trace + 19
2   libsystem_platform.dylib            0x00007fff70c1a5fd _sigtramp + 29
3   aws-crt-nodejs.node                 0x0000000102fb0008 aws_is_debugger_present.tracerPidString + 11000
4   libsystem_c.dylib                   0x00007fff70af0808 abort + 120
5   aws-crt-nodejs.node                 0x0000000102f7086b aws_fatal_assert + 75
6   aws-crt-nodejs.node                 0x0000000102f25bec s_on_connect_call + 508
7   node                                0x000000010004afb9 _ZN12_GLOBAL__N_16v8impl18ThreadSafeFunction6IdleCbEP9uv_idle_s + 413
8   node                                0x00000001009dccd2 uv__run_idle + 148
9   node                                0x00000001009d7707 uv_run + 320
10  node                                0x0000000100041ef0 _ZN4node5StartEPN2v87IsolateEPNS_11IsolateDataERKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENSA_ISC_EEEESG_ + 946
11  node                                0x0000000100040f83 _ZN4node5StartEP9uv_loop_sRKNSt3__16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEESD_ + 329
12  node                                0x0000000100040c45 _ZN4node5StartEiPPc + 681
13  node                                0x0000000100001034 start + 52
```

**Comment by Th3G4mbl3r** [comment]
Figured out the issue. The topic name being connected to was wrong.
